/**:
  ros__parameters:
    wheel_radius: 0.3461 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.235 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 3.128 # between front wheel center and rear wheel center
    wheel_tread: 1.645 # between left wheel center and right wheel center
    front_overhang: 0.952 # between front wheel center and vehicle front
    rear_overhang: 0.897 # between rear wheel center and vehicle rear
    left_overhang: 0.304 # between left wheel center and vehicle left
    right_overhang: 0.304 # between right wheel center and vehicle right
    vehicle_height: 2.320
    max_steer_angle: 0.610865 # [rad]

# EDGAR wheels: 235/50 R18 101H
